language: node_js
node_js:
- 8.4.0
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: PqoxKFXGexLMnvReBeysOMORMFLXF9xa342gKMVssT8HebaOPBU+3cSw5mVs7/zL/MmUyEBd/zKiFQ+5bUC22wQDJZ2JerMedTIcaa2XKZ9WQUoCXUnixO+zEYXRjOEx7W6jkKmM1J8qgsFhJPI49/fFvYCGdUzO2VS3FAMv2cg/5pQk1EJvQooih7B5XUb7BA54VUcwPQ7cbA7GQuHqhav2dcwz4yFEPVOzY+Y2OkxKDJi3jBl2suagIwf/z6L7R/nnp+QD6H64mPhYX/4LpLG47CQBwFIY/kk/GIm6Z2T9E4fqdG9KPsqGGQT8FkrJePl7MAj5nlkmWgdUQ7F98qRkV1Wg9HF8BSc8ozYarkf0KAQQc6pLZJNZOt2/cI34Wj1zTG6YzTIDaPUKetL+ZtbAT0UCk0XM/vA/k1AmLBrtZ5xRWI4ea8z12T2fYWWc7rwItt2zryiA1Rr1S+PaZdzEDBvQ6+sT6YvTjeV8YbAMtkDM101raq8UvFPZmVx6txzc//jxIhDkIVTh2TSCSjeBs+uFJ3V2LCbEakvhuh+vYT4dVCXcqvLd726PRmubbCWkXZg/PRKQC+pFGB8s+nsjtstilfIytX1r08jg+WsVPokV755PZN5M6tW7l5HIe6RajJgWCBzYA3qOC1cJQzjNs10nkUC4Rt6uCYIAXmU=
