language: node_js
node_js:
- 8.4.0
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: nne4fOChCrx99J9IrE5/FHa/Le76wk1SF/P9PEuZMzP8PUJLYUwlmQcR9MuQl6loqEXcxDzKiuBDZqN3PxczeNV4OR7VnrwZkUsXGesu7qcPIHQLoz+HuYzYGRb6Rb2QsHBhsh2/9hkhpd4UfPxTQvxKSb0j6B3OnJoSVqxz7T2I8W9f/Tg4bBG50njm6kitJ794/cT/RsguK92dNL91vrWivM6HxFQTKNrbnpCrpclDfHxBLx7Y3LnIUKrDZyXEZs3i1fvgCxxVhsE5ehCGPQXMEplpUXSD6MBXD0lfwGBUbF9YNLVS23yoTwU6Ka9iYx8eJFeBrV4ihfgpkRotBE5SMZDz9v5STGXDSmoXEDQKCYX1Jl1QBHJj7eQAd5fSjS9iZyRDuxspqjV4s5sCUsjXE2o5b9TAdthmSdL3GmGjyQI5YjeHdRKdhDfkZpKbryCv+9LzwdjIEg8VoGOk82dAFCEoHZczBPqGUkVAHMQM88n3XMm2S37bWYNLLVdZC336QvGoW1QU2eHb0/JCnpj5K9XIiPKx6OPW/K9TodfwJ5R/pHgKq3nCFR1Yq2tXwuiIY90XCRoCkJhYdFD6pZzF83ae0+z9cH5LghCF7mP85CfNViJHI3jFuw1L2BNJ9QMxPSTCnr5muCToEnsjhfRb81EjPg3+bmymqsZwf2s=
